name: Container Image Security Scan

on:
  workflow_dispatch:
  schedule:
    - cron: "0 18 * * 6" # Every week on Saturday at 6pm

env:
  SYSDIG_URL: https://app.au1.sysdig.com
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-vuln
  BYPASS_SCAN_FAIL: false

jobs:
  scan_images:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Sysdig CLI Scanner
      run: |
        curl -LO "https://download.sysdig.com/scanning/bin/sysdig-cli-scanner/$(curl -L -s https://download.sysdig.com/scanning/sysdig-cli-scanner/latest_version.txt)/linux/amd64/sysdig-cli-scanner"
        chmod +x ./sysdig-cli-scanner
        
       
        
        wget -q https://download.sysdig.com/stable/cli/sysdig-inline-scan-latest-linux-amd64 -O /tmp/sysdig-inline-scan
        sudo mv /tmp/sysdig-inline-scan /usr/local/bin/sysdig-inline-scan
        sudo chmod +x /usr/local/bin/sysdig-inline-scan
        sysdig-inline-scan --version

    - name: Scan Docker images
      run: |
        # Define your Docker image names here
        images=("nginx:1.24.0-alpine" "redis:7.0.15-alpine")
        for image in "${images[@]}"
        do
          SECURE_API_TOKEN=${{ secrets.SECURE_API_TOKEN }} ./sysdig-cli-scanner --apiurl ${{env.SYSDIG_URL}} "$image" || ${{ env.BYPASS_SCAN_FAIL }}
        done
